In [4]:
import pandas as pd 
import numpy as np 
import os

In [5]:
curr_path = os.getcwd()
print(curr_path)

c:\Users\priya\OneDrive\Desktop\NETWORKMED_PROJ\promiscuity_index

In [7]:
drug_target_intertaction = pd.read_csv('../raw_data/drug.target.interaction.tsv.gz',sep="\t", compression="gzip")

In [9]:
drug_target_intertaction.sample(5)

,DRUG_NAME,STRUCT_ID,TARGET_NAME,TARGET_CLASS,ACCESSION,GENE,SWISSPROT,ACT_VALUE,ACT_UNIT,ACT_TYPE,ACT_COMMENT,ACT_SOURCE,RELATION,MOA,MOA_SOURCE,ACT_SOURCE_URL,MOA_SOURCE_URL,ACTION_TYPE,TDL,ORGANISM
2385,citalopram,663,5-hydroxytryptamine receptor 2B,GPCR,P41595,HTR2B,5HT2B_HUMAN,5.931,NaN,Ki,DRUGMATRIX: Serotonin (5-Hydroxytryptamine) 5-...,DRUG MATRIX,=,NaN,NaN,NaN,NaN,NaN,Tclin,Homo sapiens
16326,zinc chloride,4344,G-protein coupled receptor 39,GPCR,O43194,GPR39,GPR39_HUMAN,8.440,NaN,EC50,NaN,CHEMBL,=,NaN,NaN,NaN,NaN,NaN,Tchem,Homo sapiens
17696,nivolumab,4923,Programmed cell death protein 1,Membrane receptor,Q15116,PDCD1,PDCD1_HUMAN,9.140,NaN,Kd,NaN,IUPHAR,=,1.0,SCIENTIFIC LITERATURE,https://pubmed.ncbi.nlm.nih.gov/24872026,https://pubmed.ncbi.nlm.nih.gov/24872026,ANTIBODY BINDING,Tclin,Homo sapiens
8060,mianserin,1796,5-hydroxytryptamine receptor 1B,GPCR,P28564,Htr1b,5HT1B_RAT,5.330,NaN,Ki,Binding affinity (Ki) to rat cortical membrane...,CHEMBL,=,NaN,NaN,NaN,NaN,NaN,NaN,Rattus norvegicus
6724,ketoconazole,1527,Multidrug resistance protein 1,Transporter,P08183,ABCB1,MDR1_HUMAN,6.000,NaN,Ki,NaN,WOMBAT-PK,=,NaN,NaN,NaN,NaN,NaN,Tchem,Homo sapiens

we only need homo sapiens

In [11]:
drug_target_human = drug_target_intertaction[drug_target_intertaction['ORGANISM']=='Homo sapiens']
drug_target_human.head()

,DRUG_NAME,STRUCT_ID,TARGET_NAME,TARGET_CLASS,ACCESSION,GENE,SWISSPROT,ACT_VALUE,ACT_UNIT,ACT_TYPE,ACT_COMMENT,ACT_SOURCE,RELATION,MOA,MOA_SOURCE,ACT_SOURCE_URL,MOA_SOURCE_URL,ACTION_TYPE,TDL,ORGANISM
0,levobupivacaine,4,Potassium voltage-gated channel subfamily H me...,Ion channel,Q12809,KCNH2,KCNH2_HUMAN,4.890,NaN,IC50,Inhibition of wild-type human ERG channel expr...,CHEMBL,=,NaN,NaN,NaN,NaN,NaN,Tclin,Homo sapiens
1,levobupivacaine,4,Sodium channel protein type 1 subunit alpha,Ion channel,P35498,SCN1A,SCN1A_HUMAN,5.790,NaN,IC50,NaN,WOMBAT-PK,=,NaN,NaN,NaN,NaN,NaN,Tclin,Homo sapiens
2,levobupivacaine,4,Sodium channel protein type 4 subunit alpha,Ion channel,P35499,SCN4A,SCN4A_HUMAN,NaN,NaN,NaN,NaN,WOMBAT-PK,NaN,1.0,CHEMBL,NaN,https://www.ebi.ac.uk/chembl/compound/inspect/...,BLOCKER,Tclin,Homo sapiens
3,levobupivacaine,4,Prostaglandin E2 receptor EP1 subtype,GPCR,P34995,PTGER1,PE2R1_HUMAN,NaN,NaN,NaN,NaN,WOMBAT-PK,NaN,NaN,NaN,NaN,NaN,NaN,Tclin,Homo sapiens
4,levobupivacaine,4,Cytochrome P450 2D6,Enzyme,P10635,CYP2D6,CP2D6_HUMAN,6.707,NaN,IC50,"DRUGMATRIX: CYP450, 2D6 enzyme inhibition (sub...",DRUG MATRIX,=,NaN,NaN,NaN,NaN,NaN,Tclin,Homo sapiens

In [16]:
promiscuity_df =    drug_target_human.groupby('DRUG_NAME')['GENE'].nunique().reset_index()
promiscuity_df.head()

            DRUG_NAME  GENE
0     (S)-nicardipine     1
1    (S)-nitrendipine     4
2    Florbetapir F-18     1
3  Flutemetamol (18F)     1
4           Vitamin E     2

In [20]:
promiscuity_df.columns = ['Drug_name','Promiscuity_index']
promiscuity_df.head()

            Drug_name  Promiscuity_index
0     (S)-nicardipine                  1
1    (S)-nitrendipine                  4
2    Florbetapir F-18                  1
3  Flutemetamol (18F)                  1
4           Vitamin E                  2

In [22]:
promiscuity_df['Drug_name'] = promiscuity_df['Drug_name'].str.lower()

In [27]:

promiscuity_df.sort_values(by='Promiscuity_index', ascending=False).to_csv('../processed_data/promiscuity_index.csv', index=False)