c:\Users\priya\OneDrive\Desktop\NETWORKMED_PROJ

In [14]:
ppi.head()

                protein1 protein2 combined_score
0  9606.ENSP00000000233 9606.ENSP00000257770 311
1  9606.ENSP00000000233 9606.ENSP00000226004 161
2  9606.ENSP00000000233 9606.ENSP00000434442 499
3  9606.ENSP00000000233 9606.ENSP00000262455 531
4  9606.ENSP00000000233 9606.ENSP00000303145 499

In [17]:
p_info = pd.read_csv('raw_data/protein_info.txt.gz',sep='\t',compression='gzip')

In [18]:
p_info.head()

,#string_protein_id,preferred_name,protein_size,annotation
0,9606.ENSP00000000233,ARF5,180,ADP-ribosylation factor 5; GTP-binding protein...
1,9606.ENSP00000000412,M6PR,277,Cation-dependent mannose-6-phosphate receptor;...
2,9606.ENSP00000001008,FKBP4,459,"Peptidyl-prolyl cis-trans isomerase FKBP4, N-t..."
3,9606.ENSP00000001146,CYP26B1,512,Cytochrome P450 26B1; Involved in the metaboli...
4,9606.ENSP00000002125,NDUFAF7,441,"Protein arginine methyltransferase NDUFAF7, mi..."